### ISSUE TITLE
has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by micklafisch** [TA2k/ioBroker.heizoel#1]
aktuelle Meldungen im Log:

`<html>
<body>

heizoel.0 | 2022-01-18 09:41:09.442 | info | State value to set for "heizoel.0.1500.data03.dealer.rating.averageRating" has to be type "number" but received type "string"
-- | -- | -- | --
heizoel.0 | 2022-01-18 09:41:09.440 | info | State value to set for "heizoel.0.1500.data02.dealer.rating.averageRatingLastYear" has to be type "number" but received type "string"
heizoel.0 | 2022-01-18 09:41:09.143 | info | State value to set for "heizoel.0.dynamic.data04.dealer.rating.averageRatingLastYear" has to be type "number" but received type "string"
heizoel.0 | 2022-01-18 09:41:09.143 | info | State value to set for "heizoel.0.dynamic.data04.dealer.rating.averageRating" has to be type "number" but received type "string"

</body>
</html>`

**Comment by TA2k** [comment]
Was sind da für Werte enthalten. Wenn man den ordner rating lösche und neustartet ist der fehler weg?

**Comment by micklafisch** [comment]
z.B. Inhalt des Ratingfeldes: 4.835303776683086 
Ich habe die betroffenen Ratings gelöscht und den Adapter neu gestartet - bislang ist ruhe.
Danke.
