### ISSUE TITLE
Bio Heizöl fehlt in der Auswahl

### ISSUE THREAD

**Issue by kortos** [TA2k/ioBroker.heizoel#3]
Hallo,
danke für den tollen Adapter. Ich bin gerade dabei den Adapter für mich einzurichten.
Dabei ist mir aufgefallen, dass der Öltyp "BIO 10%" noch in der Auswahl fehlt.
Könntest Du den noch mit aufnehmen?

LG Matthias

**Comment by TA2k** [comment]
Sehe die auswahl bei esyoil nicht

**Comment by kortos** [comment]
Bei mir gibt es hier folgende Auswahl:

![1E1F11C0-2F5D-49C0-8657-7546FF00022F](https://user-images.githubusercontent.com/8116917/153770042-ca3cecac-f9d3-4d2b-a976-f5ad9264db4f.jpeg)

**Comment by TA2k** [comment]
habs hinzugefügt
